### ISSUE TITLE
SPARQL Query Results JSON Format Errata

### ISSUE THREAD

**Issue by afs** [w3c/sparql-results-json#5]
From https://www.w3.org/2013/sparql-errata#sparql11-results-json

- [x] https://www.w3.org/2013/sparql-errata#errata-json-results-1 (error in tests not the document, correct in [rdf-test CG](https://github.com/w3c/rdf-tests/))
- [ ] https://www.w3.org/2013/sparql-errata#errata-json-results-2 - wrong link for output.srx

**Comment by rubensworks** [comment]
Shall we consider https://www.w3.org/2013/sparql-errata#errata-json-results-1 resolved, since it has been fixed in https://github.com/w3c/rdf-tests/commit/43b0eb9078f144c0d1c36f2c751b81922030eb1a ?

**Comment by afs** [comment]
Yes - I'm expecting that this WG will have tests for new features (quoted triples, text direction, canonicalization) and isn't changing or reissuing tests from RDF 1.1 or SPARQL 1.1.

If that changes we may be back here.

**Comment by rubensworks** [comment]
Done in https://github.com/w3c/sparql-results-json/pull/8
