### ISSUE TITLE
JSON Schema for SPARQL results

### ISSUE THREAD

**Issue by domel** [w3c/sparql-results-json#9]
It's worth considering a more formal JSON structure description. Similar to XML results have XML Schema (and RNG/RNC), we can define [JSON Schema](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01).

**Comment by pfps** [comment]
Is this within the charter of the working group?

**Comment by domel** [comment]
Clarifying the structure of documents. It wasn't possible when RDF 1.1 was being created because there was no JSON Schema, now it's possible, thanks to which readers can check what was only described so far. This does not change the format of the data in any way. By the way, there is a schema in the XML version, I see no reason why it shouldn't be in JSON.

**Comment by pfps** [comment]
This doesn't address whether the work is in the charter of the working group.  What part of the charter involves clarifying the structure of documents?

**Comment by domel** [comment]
It seems to me that the charter is written quite generally, so I would not expect a mention of JSON Schema (or the vast majority of PRs that have been or are waiting to be merged). I guess this part covers your concerns.

> The Working Group will also consider allowing new features in these recommendations, according to Section 6.3.11.4 of the W3C process, in order to render future evolutions easier.

**Comment by pfps** [comment]
I had looked at that.  I think that the section means that the documents could be updated to include wording about adding new features, not that new features could be added to RDF or SPARQL by the working group.

**Comment by afs** [comment]
What we have is a contribution of material to bring SPARQL JSON results to the same level as the XML results document with a schema to go with the descriptive text. SPARQL 1.1 JSON results documents remain valid, and invalid results documents remain invalid.

**Comment by pfps** [comment]
If the schema is not correct then it is a definite problem.  Does the working group want to devote resources for a review of the schema?

**Comment by afs** [comment]
There is already discussion and testing on the PR.
